# Generated by Django 4.2 on 2023-04-17 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_gymowner_customuser_admin_gym_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
