# Generated by Django 4.2 on 2023-04-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(to='core.exercise'),
        ),
    ]
