# Generated by Django 4.2 on 2023-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exerciseplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Trainer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=170.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
