# Generated by Django 4.2 on 2023-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userplan_delete_exerciseplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
