# Generated by Django 4.2 on 2023-06-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_customuser_subscription_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
