# Generated by Django 4.2 on 2023-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='day',
            field=models.CharField(default='Saturday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.CharField(default='11 a.m.', max_length=10),
            preserve_default=False,
        ),
    ]
