# Generated by Django 4.2 on 2023-04-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.DeleteModel(
            name='Gyms',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
